openapi: 3.0.0
info:
  title: Backend API WEB UI Artajasa
  version: '1.0'
  description: The API documentation here contains all the API documentation to support the WEB UI ARTAJASA
servers:
  - url: 'https://your-production-url.com' # Gantilah dengan URL produksi yang sesuai
    description: Production Environment
  - url: 'https://your-staging-url.com' # Gantilah dengan URL staging yang sesuai
    description: Staging Environment
  - url: 'http://localhost:8070'
    description: Development Environment
paths:
  /api/users:
    post:
      summary: Create Finance Testing Account
      operationId: post-api-users
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      username:
                        type: string
                      role:
                        type: string
                      password:
                        type: string
                examples:
                  Example 1:
                    value:
                      status: true
                      message: Account berhasil dibuat
                      data:
                        id: 1
                        username: testing1
                        password: testing1pass
                        role: client
                        status: active
        '400':
          description: Error
        '403':
          description: Username already used
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                role:
                  type: string
                status:
                  type: string
              examples:
                Example 1:
                  value:
                    username: testing1
                    password: Testing1
                    role: client
                    status: active
        description: In this body you can create a new finance account for testing
      description: ''
      tags:
        - Users Endpoint
      parameters:
        - schema:
            type: string
          in: header
          required: true
          name: Authorization
  
  /api/users/login:
    post:
      summary: Login users
      operationId: post-api-users-login
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                      payload:
                        type: object
                        properties:
                          id:
                            type: string
                          username:
                            type: string
                          role:
                            type: string
              
                examples:
                  Example 1:
                    value:
                      status: true
                      message: Login Success
                      data:
                        token: your-token
                        payload:
                          id: 1
                          username: Admin5
                          role: client
                          status: active
        '400':
          description: Error
        '403':
          description: Username already used
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              examples:
                Example 1:
                  value:
                    username: Lintangs
                    password: Litang5
        description: In this body you can login
      description: ''
      tags:
        - Users Endpoint
     
components:
  securitySchemes: {}
